# Exercise #1

1. Create a two dimensional array populated with the numbers 0 to 63. The array should have a shape of 4 rows and 16 columns.

In [51]:
# Step 1 Solution Here

import numpy as np

arr = np.arange(64, dtype=np.int8).reshape(4,16)

arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63]],
      dtype=int8)

2. Using the array created in the previous step, display the following:

- Element Data Type
- Number of Dimensions
- Shape
- Element Count
- Item Size in Bytes
- Array Size in Bytes

In [52]:
# Step 2 Solution Here

display(arr.dtype)
display(arr.ndim)
display(arr.shape)
display(arr.size)
display(arr.itemsize)
display(arr.nbytes)

dtype('int8')

2

(4, 16)

64

1

64

3. Subtract 10 from each element through a one-line subtraction operation.

In [53]:
# Step 3 Solution Here

new_arr = arr - 10

display(arr)
display(new_arr)

arr -= 10

display(arr)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63]],
      dtype=int8)

array([[-10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,
          3,   4,   5],
       [  6,   7,   8,   9,  10,  11,  12,  13,  14,  15,  16,  17,  18,
         19,  20,  21],
       [ 22,  23,  24,  25,  26,  27,  28,  29,  30,  31,  32,  33,  34,
         35,  36,  37],
       [ 38,  39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,
         51,  52,  53]], dtype=int8)

array([[-10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,
          3,   4,   5],
       [  6,   7,   8,   9,  10,  11,  12,  13,  14,  15,  16,  17,  18,
         19,  20,  21],
       [ 22,  23,  24,  25,  26,  27,  28,  29,  30,  31,  32,  33,  34,
         35,  36,  37],
       [ 38,  39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,
         51,  52,  53]], dtype=int8)

4. Multiply all even values with a -1.

In [54]:
# Step 4 Solution Here

# even_mask = arr % 2 == 0

# arr[even_mask]

# arr[even_mask] = arr[even_mask] * -1

arr[arr % 2 == 0] *= -1

arr

array([[ 10,  -9,   8,  -7,   6,  -5,   4,  -3,   2,  -1,   0,   1,  -2,
          3,  -4,   5],
       [ -6,   7,  -8,   9, -10,  11, -12,  13, -14,  15, -16,  17, -18,
         19, -20,  21],
       [-22,  23, -24,  25, -26,  27, -28,  29, -30,  31, -32,  33, -34,
         35, -36,  37],
       [-38,  39, -40,  41, -42,  43, -44,  45, -46,  47, -48,  49, -50,
         51, -52,  53]], dtype=int8)

5. Replace all negative numbers with the NaN value. You may need to change data type.

In [60]:
# Step 5 Solution

new_arr = np.where(arr < 0, 1000, arr) # if I am changing the type, this is a little cleaner

# arr = arr.astype(np.float16)
arr[arr < 0] = 40 # if I am doing an inplace update with same type, this is better

# print(id(arr) == id(new_arr))

x = 0

new_arr[x,0] = 50

print(new_arr.dtype)
display(new_arr)
display(arr)

int16


array([[50, 40,  8, 40,  6, 40,  4, 40,  2, 40,  0,  1, 40,  3, 40,  5],
       [40,  7, 40,  9, 40, 11, 40, 13, 40, 15, 40, 17, 40, 19, 40, 21],
       [40, 23, 40, 25, 40, 27, 40, 29, 40, 31, 40, 33, 40, 35, 40, 37],
       [40, 39, 40, 41, 40, 43, 40, 45, 40, 47, 40, 49, 40, 51, 40, 53]],
      dtype=int16)

array([[10, 40,  8, 40,  6, 40,  4, 40,  2, 40,  0,  1, 40,  3, 40,  5],
       [40,  7, 40,  9, 40, 11, 40, 13, 40, 15, 40, 17, 40, 19, 40, 21],
       [40, 23, 40, 25, 40, 27, 40, 29, 40, 31, 40, 33, 40, 35, 40, 37],
       [40, 39, 40, 41, 40, 43, 40, 45, 40, 47, 40, 49, 40, 51, 40, 53]],
      dtype=int8)

6. Transform the 2d array into a 1d array. Drop all of the NaN values.

In [27]:
# Step 6 Solution

# arr[np.logical_not(np.isnan(arr))]



display(arr[~(np.isnan(arr))])

display(arr)

array([10.,  8.,  6.,  4.,  2.,  0.,  1.,  3.,  5.,  7.,  9., 11., 13.,
       15., 17., 19., 21., 23., 25., 27., 29., 31., 33., 35., 37., 39.,
       41., 43., 45., 47., 49., 51., 53.], dtype=float16)

array([[10., nan,  8., nan,  6., nan,  4., nan,  2., nan,  0.,  1., nan,
         3., nan,  5.],
       [nan,  7., nan,  9., nan, 11., nan, 13., nan, 15., nan, 17., nan,
        19., nan, 21.],
       [nan, 23., nan, 25., nan, 27., nan, 29., nan, 31., nan, 33., nan,
        35., nan, 37.],
       [nan, 39., nan, 41., nan, 43., nan, 45., nan, 47., nan, 49., nan,
        51., nan, 53.]], dtype=float16)